# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/josh/Documents/projects/chroma-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/josh/Documents/projects/chroma-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/josh/Documents/projects/chroma-engine/CMakeFiles /home/josh/Documents/projects/chroma-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/josh/Documents/projects/chroma-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chroma-engine

# Build rule for target.
chroma-engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chroma-engine
.PHONY : chroma-engine

# fast build rule for target.
chroma-engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/build
.PHONY : chroma-engine/fast

src/chrome-engine.o: src/chrome-engine.c.o
.PHONY : src/chrome-engine.o

# target to build an object file
src/chrome-engine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/chrome-engine.c.o
.PHONY : src/chrome-engine.c.o

src/chrome-engine.i: src/chrome-engine.c.i
.PHONY : src/chrome-engine.i

# target to preprocess a source file
src/chrome-engine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/chrome-engine.c.i
.PHONY : src/chrome-engine.c.i

src/chrome-engine.s: src/chrome-engine.c.s
.PHONY : src/chrome-engine.s

# target to generate assembly for a file
src/chrome-engine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/chrome-engine.c.s
.PHONY : src/chrome-engine.c.s

src/engine.o: src/engine.c.o
.PHONY : src/engine.o

# target to build an object file
src/engine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/engine.c.o
.PHONY : src/engine.c.o

src/engine.i: src/engine.c.i
.PHONY : src/engine.i

# target to preprocess a source file
src/engine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/engine.c.i
.PHONY : src/engine.c.i

src/engine.s: src/engine.c.s
.PHONY : src/engine.s

# target to generate assembly for a file
src/engine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/engine.c.s
.PHONY : src/engine.c.s

src/geometry/g_annulus.o: src/geometry/g_annulus.c.o
.PHONY : src/geometry/g_annulus.o

# target to build an object file
src/geometry/g_annulus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/g_annulus.c.o
.PHONY : src/geometry/g_annulus.c.o

src/geometry/g_annulus.i: src/geometry/g_annulus.c.i
.PHONY : src/geometry/g_annulus.i

# target to preprocess a source file
src/geometry/g_annulus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/g_annulus.c.i
.PHONY : src/geometry/g_annulus.c.i

src/geometry/g_annulus.s: src/geometry/g_annulus.c.s
.PHONY : src/geometry/g_annulus.s

# target to generate assembly for a file
src/geometry/g_annulus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/g_annulus.c.s
.PHONY : src/geometry/g_annulus.c.s

src/geometry/g_circle.o: src/geometry/g_circle.c.o
.PHONY : src/geometry/g_circle.o

# target to build an object file
src/geometry/g_circle.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/g_circle.c.o
.PHONY : src/geometry/g_circle.c.o

src/geometry/g_circle.i: src/geometry/g_circle.c.i
.PHONY : src/geometry/g_circle.i

# target to preprocess a source file
src/geometry/g_circle.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/g_circle.c.i
.PHONY : src/geometry/g_circle.c.i

src/geometry/g_circle.s: src/geometry/g_circle.c.s
.PHONY : src/geometry/g_circle.s

# target to generate assembly for a file
src/geometry/g_circle.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/g_circle.c.s
.PHONY : src/geometry/g_circle.c.s

src/geometry/g_rect.o: src/geometry/g_rect.c.o
.PHONY : src/geometry/g_rect.o

# target to build an object file
src/geometry/g_rect.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/g_rect.c.o
.PHONY : src/geometry/g_rect.c.o

src/geometry/g_rect.i: src/geometry/g_rect.c.i
.PHONY : src/geometry/g_rect.i

# target to preprocess a source file
src/geometry/g_rect.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/g_rect.c.i
.PHONY : src/geometry/g_rect.c.i

src/geometry/g_rect.s: src/geometry/g_rect.c.s
.PHONY : src/geometry/g_rect.s

# target to generate assembly for a file
src/geometry/g_rect.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/g_rect.c.s
.PHONY : src/geometry/g_rect.c.s

src/geometry/g_text.o: src/geometry/g_text.c.o
.PHONY : src/geometry/g_text.o

# target to build an object file
src/geometry/g_text.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/g_text.c.o
.PHONY : src/geometry/g_text.c.o

src/geometry/g_text.i: src/geometry/g_text.c.i
.PHONY : src/geometry/g_text.i

# target to preprocess a source file
src/geometry/g_text.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/g_text.c.i
.PHONY : src/geometry/g_text.c.i

src/geometry/g_text.s: src/geometry/g_text.c.s
.PHONY : src/geometry/g_text.s

# target to generate assembly for a file
src/geometry/g_text.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/g_text.c.s
.PHONY : src/geometry/g_text.c.s

src/geometry/geometry.o: src/geometry/geometry.c.o
.PHONY : src/geometry/geometry.o

# target to build an object file
src/geometry/geometry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/geometry.c.o
.PHONY : src/geometry/geometry.c.o

src/geometry/geometry.i: src/geometry/geometry.c.i
.PHONY : src/geometry/geometry.i

# target to preprocess a source file
src/geometry/geometry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/geometry.c.i
.PHONY : src/geometry/geometry.c.i

src/geometry/geometry.s: src/geometry/geometry.c.s
.PHONY : src/geometry/geometry.s

# target to generate assembly for a file
src/geometry/geometry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/geometry/geometry.c.s
.PHONY : src/geometry/geometry.c.s

src/gl_render/gl_annulus.o: src/gl_render/gl_annulus.c.o
.PHONY : src/gl_render/gl_annulus.o

# target to build an object file
src/gl_render/gl_annulus.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_annulus.c.o
.PHONY : src/gl_render/gl_annulus.c.o

src/gl_render/gl_annulus.i: src/gl_render/gl_annulus.c.i
.PHONY : src/gl_render/gl_annulus.i

# target to preprocess a source file
src/gl_render/gl_annulus.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_annulus.c.i
.PHONY : src/gl_render/gl_annulus.c.i

src/gl_render/gl_annulus.s: src/gl_render/gl_annulus.c.s
.PHONY : src/gl_render/gl_annulus.s

# target to generate assembly for a file
src/gl_render/gl_annulus.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_annulus.c.s
.PHONY : src/gl_render/gl_annulus.c.s

src/gl_render/gl_circle.o: src/gl_render/gl_circle.c.o
.PHONY : src/gl_render/gl_circle.o

# target to build an object file
src/gl_render/gl_circle.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_circle.c.o
.PHONY : src/gl_render/gl_circle.c.o

src/gl_render/gl_circle.i: src/gl_render/gl_circle.c.i
.PHONY : src/gl_render/gl_circle.i

# target to preprocess a source file
src/gl_render/gl_circle.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_circle.c.i
.PHONY : src/gl_render/gl_circle.c.i

src/gl_render/gl_circle.s: src/gl_render/gl_circle.c.s
.PHONY : src/gl_render/gl_circle.s

# target to generate assembly for a file
src/gl_render/gl_circle.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_circle.c.s
.PHONY : src/gl_render/gl_circle.c.s

src/gl_render/gl_rect.o: src/gl_render/gl_rect.c.o
.PHONY : src/gl_render/gl_rect.o

# target to build an object file
src/gl_render/gl_rect.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_rect.c.o
.PHONY : src/gl_render/gl_rect.c.o

src/gl_render/gl_rect.i: src/gl_render/gl_rect.c.i
.PHONY : src/gl_render/gl_rect.i

# target to preprocess a source file
src/gl_render/gl_rect.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_rect.c.i
.PHONY : src/gl_render/gl_rect.c.i

src/gl_render/gl_rect.s: src/gl_render/gl_rect.c.s
.PHONY : src/gl_render/gl_rect.s

# target to generate assembly for a file
src/gl_render/gl_rect.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_rect.c.s
.PHONY : src/gl_render/gl_rect.c.s

src/gl_render/gl_renderer.o: src/gl_render/gl_renderer.c.o
.PHONY : src/gl_render/gl_renderer.o

# target to build an object file
src/gl_render/gl_renderer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_renderer.c.o
.PHONY : src/gl_render/gl_renderer.c.o

src/gl_render/gl_renderer.i: src/gl_render/gl_renderer.c.i
.PHONY : src/gl_render/gl_renderer.i

# target to preprocess a source file
src/gl_render/gl_renderer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_renderer.c.i
.PHONY : src/gl_render/gl_renderer.c.i

src/gl_render/gl_renderer.s: src/gl_render/gl_renderer.c.s
.PHONY : src/gl_render/gl_renderer.s

# target to generate assembly for a file
src/gl_render/gl_renderer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_renderer.c.s
.PHONY : src/gl_render/gl_renderer.c.s

src/gl_render/gl_text.o: src/gl_render/gl_text.c.o
.PHONY : src/gl_render/gl_text.o

# target to build an object file
src/gl_render/gl_text.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_text.c.o
.PHONY : src/gl_render/gl_text.c.o

src/gl_render/gl_text.i: src/gl_render/gl_text.c.i
.PHONY : src/gl_render/gl_text.i

# target to preprocess a source file
src/gl_render/gl_text.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_text.c.i
.PHONY : src/gl_render/gl_text.c.i

src/gl_render/gl_text.s: src/gl_render/gl_text.c.s
.PHONY : src/gl_render/gl_text.s

# target to generate assembly for a file
src/gl_render/gl_text.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/gl_render/gl_text.c.s
.PHONY : src/gl_render/gl_text.c.s

src/log/log.o: src/log/log.c.o
.PHONY : src/log/log.o

# target to build an object file
src/log/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/log/log.c.o
.PHONY : src/log/log.c.o

src/log/log.i: src/log/log.c.i
.PHONY : src/log/log.i

# target to preprocess a source file
src/log/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/log/log.c.i
.PHONY : src/log/log.c.i

src/log/log.s: src/log/log.c.s
.PHONY : src/log/log.s

# target to generate assembly for a file
src/log/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/log/log.c.s
.PHONY : src/log/log.c.s

src/page/animation.o: src/page/animation.c.o
.PHONY : src/page/animation.o

# target to build an object file
src/page/animation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/page/animation.c.o
.PHONY : src/page/animation.c.o

src/page/animation.i: src/page/animation.c.i
.PHONY : src/page/animation.i

# target to preprocess a source file
src/page/animation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/page/animation.c.i
.PHONY : src/page/animation.c.i

src/page/animation.s: src/page/animation.c.s
.PHONY : src/page/animation.s

# target to generate assembly for a file
src/page/animation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/page/animation.c.s
.PHONY : src/page/animation.c.s

src/page/graphics-hub.o: src/page/graphics-hub.c.o
.PHONY : src/page/graphics-hub.o

# target to build an object file
src/page/graphics-hub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/page/graphics-hub.c.o
.PHONY : src/page/graphics-hub.c.o

src/page/graphics-hub.i: src/page/graphics-hub.c.i
.PHONY : src/page/graphics-hub.i

# target to preprocess a source file
src/page/graphics-hub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/page/graphics-hub.c.i
.PHONY : src/page/graphics-hub.c.i

src/page/graphics-hub.s: src/page/graphics-hub.c.s
.PHONY : src/page/graphics-hub.s

# target to generate assembly for a file
src/page/graphics-hub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/page/graphics-hub.c.s
.PHONY : src/page/graphics-hub.c.s

src/page/page.o: src/page/page.c.o
.PHONY : src/page/page.o

# target to build an object file
src/page/page.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/page/page.c.o
.PHONY : src/page/page.c.o

src/page/page.i: src/page/page.c.i
.PHONY : src/page/page.i

# target to preprocess a source file
src/page/page.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/page/page.c.i
.PHONY : src/page/page.c.i

src/page/page.s: src/page/page.c.s
.PHONY : src/page/page.s

# target to generate assembly for a file
src/page/page.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/page/page.c.s
.PHONY : src/page/page.c.s

src/parser/parser.o: src/parser/parser.c.o
.PHONY : src/parser/parser.o

# target to build an object file
src/parser/parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/parser/parser.c.o
.PHONY : src/parser/parser.c.o

src/parser/parser.i: src/parser/parser.c.i
.PHONY : src/parser/parser.i

# target to preprocess a source file
src/parser/parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/parser/parser.c.i
.PHONY : src/parser/parser.c.i

src/parser/parser.s: src/parser/parser.c.s
.PHONY : src/parser/parser.s

# target to generate assembly for a file
src/parser/parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/parser/parser.c.s
.PHONY : src/parser/parser.c.s

src/parser/tcp-server.o: src/parser/tcp-server.c.o
.PHONY : src/parser/tcp-server.o

# target to build an object file
src/parser/tcp-server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/parser/tcp-server.c.o
.PHONY : src/parser/tcp-server.c.o

src/parser/tcp-server.i: src/parser/tcp-server.c.i
.PHONY : src/parser/tcp-server.i

# target to preprocess a source file
src/parser/tcp-server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/parser/tcp-server.c.i
.PHONY : src/parser/tcp-server.c.i

src/parser/tcp-server.s: src/parser/tcp-server.c.s
.PHONY : src/parser/tcp-server.s

# target to generate assembly for a file
src/parser/tcp-server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/parser/tcp-server.c.s
.PHONY : src/parser/tcp-server.c.s

src/preview.o: src/preview.c.o
.PHONY : src/preview.o

# target to build an object file
src/preview.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/preview.c.o
.PHONY : src/preview.c.o

src/preview.i: src/preview.c.i
.PHONY : src/preview.i

# target to preprocess a source file
src/preview.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/preview.c.i
.PHONY : src/preview.c.i

src/preview.s: src/preview.c.s
.PHONY : src/preview.s

# target to generate assembly for a file
src/preview.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chroma-engine.dir/build.make CMakeFiles/chroma-engine.dir/src/preview.c.s
.PHONY : src/preview.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chroma-engine"
	@echo "... src/chrome-engine.o"
	@echo "... src/chrome-engine.i"
	@echo "... src/chrome-engine.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/geometry/g_annulus.o"
	@echo "... src/geometry/g_annulus.i"
	@echo "... src/geometry/g_annulus.s"
	@echo "... src/geometry/g_circle.o"
	@echo "... src/geometry/g_circle.i"
	@echo "... src/geometry/g_circle.s"
	@echo "... src/geometry/g_rect.o"
	@echo "... src/geometry/g_rect.i"
	@echo "... src/geometry/g_rect.s"
	@echo "... src/geometry/g_text.o"
	@echo "... src/geometry/g_text.i"
	@echo "... src/geometry/g_text.s"
	@echo "... src/geometry/geometry.o"
	@echo "... src/geometry/geometry.i"
	@echo "... src/geometry/geometry.s"
	@echo "... src/gl_render/gl_annulus.o"
	@echo "... src/gl_render/gl_annulus.i"
	@echo "... src/gl_render/gl_annulus.s"
	@echo "... src/gl_render/gl_circle.o"
	@echo "... src/gl_render/gl_circle.i"
	@echo "... src/gl_render/gl_circle.s"
	@echo "... src/gl_render/gl_rect.o"
	@echo "... src/gl_render/gl_rect.i"
	@echo "... src/gl_render/gl_rect.s"
	@echo "... src/gl_render/gl_renderer.o"
	@echo "... src/gl_render/gl_renderer.i"
	@echo "... src/gl_render/gl_renderer.s"
	@echo "... src/gl_render/gl_text.o"
	@echo "... src/gl_render/gl_text.i"
	@echo "... src/gl_render/gl_text.s"
	@echo "... src/log/log.o"
	@echo "... src/log/log.i"
	@echo "... src/log/log.s"
	@echo "... src/page/animation.o"
	@echo "... src/page/animation.i"
	@echo "... src/page/animation.s"
	@echo "... src/page/graphics-hub.o"
	@echo "... src/page/graphics-hub.i"
	@echo "... src/page/graphics-hub.s"
	@echo "... src/page/page.o"
	@echo "... src/page/page.i"
	@echo "... src/page/page.s"
	@echo "... src/parser/parser.o"
	@echo "... src/parser/parser.i"
	@echo "... src/parser/parser.s"
	@echo "... src/parser/tcp-server.o"
	@echo "... src/parser/tcp-server.i"
	@echo "... src/parser/tcp-server.s"
	@echo "... src/preview.o"
	@echo "... src/preview.i"
	@echo "... src/preview.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

